### ISSUE TITLE
Can't seem to burn fuses…

### ISSUE THREAD

**Issue by hedefalk** [Ttreintaysiete/ardcore#5]
I'm still waiting for a "real" AVR programmer to arrive but hooked up a Nano in the meantime. Maybe my problems are related to this, but I'll ask just if you recognize these issues:

So I have an Arduino ISP hooked up that's running the official ArduinoISP sketch. I've mounted components according to the first step here:

![image](https://user-images.githubusercontent.com/116520/34722380-fe5f70de-f546-11e7-8ab6-4395cdcf9faf.png)

I'm then trying to set the fuses with something like:

```
~ ❯❯❯  avrdude -c arduino -b  19200 -p m328p -P /dev/tty.wchusbserial1450 -U lfuse:w:0xFF:m -U hfuse:w:0xDA:m -U efuse:w:0x05:m                                                    ⏎

avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x15
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x15


avrdude: stk500_getparm(): (a) protocol error, expect=0x14, resp=0x14

avrdude: stk500_getparm(): (a) protocol error, expect=0x14, resp=0x01
avrdude: stk500_initialize(): (a) protocol error, expect=0x14, resp=0x10
avrdude: initialization failed, rc=-1
         Double check connections and try again, or use -F to override
         this check.

avrdude: stk500_disable(): unknown response=0x12

avrdude done.  Thank you.
```

I'm going to dig deeper into the Arduino stuff how to properly do this, feels like the usb connection on osx/arduino is pretty unstable. I get different errors using different baudrates too… Anyways, just wanted to check if this is something you recognized?

**Comment by hadesbox** [comment]
Depending on your linux distro and avrdude installation you may need to sudo that command!

also check that the /dev/tty.wchusbserial1450 is the correct device.. you can unplug the arduino nano, then use the __dmesg__ command to see the actual device name.

Also fuses are to let know the atmega328 it should use an external crystal which is more precise than the internal, this means that you can still BURN an arduino sketch to your ardcore (for instance the testing sketch or the blinking led sketch) and see if it works.

The only behavior you will get by not setting the fuses is that the sketch will look like if runs slower because of the internal atmega328 oscillator.

**Comment by hadesbox** [comment]
Also triple check that you connected the right pins of the header, as some may be swapped.

https://www.arduino.cc/en/Tutorial/ArduinoISP

I used the avrisp-mkii these are the headers

![mkii headers](https://lh4.googleusercontent.com/_N4orY3Ztc3M/Tcq0gtaX_gI/AAAAAAAAAKM/9fju_il9l5U/s800/avrispmkII-pin-out.jpg)

**Comment by hadesbox** [comment]
Also check this http://heliosoph.mit-links.info/arduinoisp-reading-writing-fuses-atmega328p/
instead of $ avrdude -c __arduino__ -b  19200
use $ avrdude -c __avrisp__ -b  19200

**Comment by hadesbox** [comment]
Check the

**Comment by hedefalk** [comment]
@hadesbox Thx for tips! I'm unfortunately home with sick kids and away from "stuff" again so can't do much right now, but I'll be back!

**Comment by hedefalk** [comment]
Thanks for all the help!

I've finally gotten so far that I can program other Arduinos via the ISCP header with my little homebrewed programmer. Seems what was missing was a way for me to switch between being programmed and being programmer so I added a cap between reset and gnd on the programmer that is connected via a jumper so I can pull it out if I need to reprogram the actual programmer again:
![image](https://user-images.githubusercontent.com/116520/34820017-ad975a16-f6bf-11e7-9962-30b18fa74081.png)

Before that I had all sorts of problems of the programmer being programmed and such.

So I've mostly experimented with ArduinoIDE, but with verbose output I can see the avrdude commands so it turned out when using the "Arduino as ISP" programmer in the UI it uses stk500v1 as programmer argument.

So I now I tried using the settings that have been successful but with the fuses update commands:

```

~/d/p/flatcam ❯❯❯ avrdude -v -p atmega328p -b 19200 -P /dev/cu.wchusbserial213240 -c stk500v1 -U lfuse:w:0xFF:m -U hfuse:w:0xDA:m -U efuse:w:0x05:m                                                      master

avrdude: Version 6.3, compiled on Sep 18 2017 at 20:31:51
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "/usr/local/Cellar/avrdude/6.3/etc/avrdude.conf"
         User configuration file is "/Users/viktor/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.wchusbserial213240
         Using Programmer              : stk500v1
         Overriding Baud Rate          : 19200
         AVR Part                      : ATmega328P
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PC2
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
           flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
           lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : STK500
         Description     : Atmel STK500 Version 1.x firmware
         Hardware Version: 2
         Firmware Version: 1.18
         Topcard         : Unknown
         Vtarget         : 0.0 V
         Varef           : 0.0 V
         Oscillator      : Off
         SCK period      : 0.1 us

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.08s

avrdude: Device signature = 0x000000 (retrying)

Reading | ################################################## | 100% 0.08s

avrdude: Device signature = 0x000000 (retrying)

Reading | ################################################## | 100% 0.08s

avrdude: Device signature = 0x000000
avrdude: Yikes!  Invalid device signature.
         Double check connections and try again, or use -F to override
         this check.


avrdude done.  Thank you.
```


At least some progress for me :) I'll have to dig further…

**Comment by hedefalk** [comment]
Seems I can actually use arduino as programmer argument too. Anyway, just reading the fuses from say an arduino pro mini, I get:


```
~/d/p/flatcam ❯❯❯ avrdude -p atmega328p -b 19200 -P /dev/cu.wchusbserial213240 -c arduino                                                                                                                master

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.03s

avrdude: Device signature = 0x1e950f (probably m328p)

avrdude: safemode: Fuses OK (E:FD, H:DA, L:FF)

avrdude done.  Thank you.
```

An Arduino Uno:

```
~/d/p/flatcam ❯❯❯ avrdude -p atmega328p -b 19200 -P /dev/cu.wchusbserial213240 -c arduino                                                                                                                master

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.03s

avrdude: Device signature = 0x1e950f (probably m328p)

avrdude: safemode: Fuses OK (E:FD, H:DE, L:FF)

avrdude done.  Thank you.
``` 

But on my ardcore board:

```
~/d/p/flatcam ❯❯❯ avrdude -p atmega328p -b 19200 -P /dev/cu.wchusbserial213240 -c arduino                                                                                                                master

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.03s

avrdude: Device signature = 0x000000 (retrying)

Reading | ################################################## | 100% 0.03s

avrdude: Device signature = 0x000000 (retrying)

Reading | ################################################## | 100% 0.03s

avrdude: Device signature = 0x000000
avrdude: Yikes!  Invalid device signature.
         Double check connections and try again, or use -F to override
         this check.


avrdude done.  Thank you.
```

Anyway, I'll start digging into this problem, one suggestion was that usb power might be to low, but doesn't make sense if it works for other arduino boards being powered the same way.

I've checked the soldering and everything seems fine, but I haven't done much extensive testing more than checking for any bridges on the MCU. Might have fried stuff doing my first hot air SMD too though :)

**Comment by hedefalk** [comment]
Checked with my scope and I have no oscillation on the crystal :/ Hard to look under that little bugger if the soldering is bad…

**Comment by hedefalk** [comment]
Oh, maybe this is normal and what the update to the fuses are for I realize…

**Comment by hadesbox** [comment]
I normally check that the pins of the resonator (crystal + caps in a single encapsulated) are not shorted to each other... check that first.

Then try to check if there is conductivity between the 3 legs of the resonator and the corresponding 2 legs in the 328, the mid pad of the resonator should be connected to a trace that goes south to a cap I think.

**Comment by hedefalk** [comment]
Thanks! Yes, all those seem fine - as far as a bit of solder sticking out under the resonator for each pad at least.

- [x] left resonator pad to pin 7 on MCU connected
- [x] right resonator pad to pin 8 on MCU connected
- [x] middle resonator pad connected to C2/GND
- [x] no shorts between resonator pads

**Comment by hadesbox** [comment]
I dont know what are the voltage levels of the resonator, the frequency should be 8Mhz of course... My scope is broken so I can't test it right now.

**Comment by hedefalk** [comment]
Please don't mind me if you have better things to do, but if ok with you, I'll use this ticket to track my debugging.

Just found that I have only 0.14V between Vcc and GND on the Ardcore MCU, pin 4 and 3. So that's bad, I guess either fried or there's something else. At this point I'm considering powering up 5V with a lab PSU just to make sure…

Oh, but I have 4.8V on the regulator output pin.

Ah, found it, bad soldering on the MCU. Pin 4 isn't properly connected so no power.

**Comment by averia** [comment]
Hi, its necessary connect the ardcore to the PSU for upload the scketches and change the fuses. 
I say that because in the photo you don´t have the cable

**Comment by hedefalk** [comment]
@averia Oh, really? Why is that? 

Yeah, I have only powered it with 5V directly from ICSP header… That works for other Atmega328p's I've tried though…?

But I was thinking yeah, because it's on board with a regulator, maybe stuff get's sucked in backwards :) (noob analysis :) )

**Comment by hedefalk** [comment]
An update is that I fixed the bad soldering, everything I've tried checks out, power pins and stuff on the MCU are correct, no oscillation from the oscillator (I have compared to a working arduino with the scope where I CAN see sine waves on both xtal pins). But I figured that was as expected if it uses the internal crystal before setting the fuses. But I can't even read the fuses. My suspicion is I've actually fried it while doing my first smd soldering. 

I have boards and components to make 10 of these so I'm gonna try to redo it instead and see if I have the same results.

But definitely gonna try to connect to 12V rail first if that's a suggestion.

**Comment by hadesbox** [comment]
As Averia says, the 5vs from the ISCP doesn't power the atmega you definitively need to plug it to +12v :), let us know how everything went and if we can help you.

**Comment by hedefalk** [comment]
I've tried it now with external eurorack power, but same result. I have the same voltage, 4.71 on the atmega as before when only using ICSP power:

![image](https://user-images.githubusercontent.com/116520/34874587-dc6a7668-f799-11e7-8a69-f04b1e21f5ed.png)

I'm still suspecting a fried MCU, so will go ahead and make another one, but will have to wait until next week at best. My heatgun started smoking yesterday :/

The result on a pro mini clone using only ICSP power is:

```
~ ❯❯❯ avrdude -p atmega328p -b 19200 -P /dev/cu.wchusbserial212240 -c stk500v1                                                                                                   ⏎

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.08s

avrdude: Device signature = 0x1e950f (probably m328p)

avrdude: safemode: Fuses OK (E:FD, H:DA, L:FF)

avrdude done.  Thank you.

```


The result I have on my ardcore is the exact same as just leaving the ICSP header unconnected:


```
~ ❯❯❯ avrdude -p atmega328p -b 19200 -P /dev/cu.wchusbserial212240 -c stk500v1

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.08s

avrdude: Device signature = 0x000000 (retrying)

Reading | ################################################## | 100% 0.08s

avrdude: Device signature = 0x000000 (retrying)

Reading | ################################################## | 100% 0.08s

avrdude: Device signature = 0x000000
avrdude: Yikes!  Invalid device signature.
         Double check connections and try again, or use -F to override
         this check.


avrdude done.  Thank you
```

**Comment by hedefalk** [comment]
Could you elaborate on the reason I need external power other than the ICSP one? I you know that is, or maybe just from experience?

**Comment by hadesbox** [comment]
Because I didnt connect that trace into the Atmega. It was a design decission .. .because its dangerous to have the ISCP header and the +5V from rail together, if I wanted to have both then I need to add a jumper to make a switch so the user can select where from he wants to powers the MCU from the USB of the programmer or the eurorack power.

**Comment by hedefalk** [comment]
Yey! Fuses read!

```
~ ❯❯❯ avrdude -p atmega328p -b 19200 -P /dev/cu.wchusbserial212240 -c stk500v1                                                                                                   ⏎

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.08s

avrdude: Device signature = 0x1e950f (probably m328p)

avrdude: safemode: Fuses OK (E:FF, H:D9, L:62)

avrdude done.  Thank you.
```

This with only ISCP though. The +5V is actually connected :)

It was bad soldering again. I was really really sure I had tested this thorough but apparently not. I checked (thought it was triple checking) the connection of each ICSP pin header to the top of the legs on the MCU and noticed that the SCK wasn't soldered properly on the MCU.

Thanks for all the help!

**Comment by hadesbox** [comment]
Then thats it! :) I could be mistake on the power thing I said, but generally we burn the arduino sketch with the power up.

**Comment by hedefalk** [comment]
@hadesbox ok, cool! Do you manufacture a lot of these?

Anyway, now settings fuses I get some safemore verification error, is this fine?

```
~ ❯❯❯ avrdude -p atmega328p -b 19200 -P /dev/cu.wchusbserial212240 -c stk500v1 -U lfuse:w:0xFF:m -U hfuse:w:0xDA:m -U efuse:w:0x05:m

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.08s

avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: reading input file "0xFF"
avrdude: writing lfuse (1 bytes):

Writing | ################################################## | 100% 0.08s

avrdude: 1 bytes of lfuse written
avrdude: verifying lfuse memory against 0xFF:
avrdude: load data lfuse data from input file 0xFF:
avrdude: input file 0xFF contains 1 bytes
avrdude: reading on-chip lfuse data:

Reading | ################################################## | 100% 0.03s

avrdude: verifying ...
avrdude: 1 bytes of lfuse verified
avrdude: reading input file "0xDA"
avrdude: writing hfuse (1 bytes):

Writing | ################################################## | 100% 0.08s

avrdude: 1 bytes of hfuse written
avrdude: verifying hfuse memory against 0xDA:
avrdude: load data hfuse data from input file 0xDA:
avrdude: input file 0xDA contains 1 bytes
avrdude: reading on-chip hfuse data:

Reading | ################################################## | 100% 0.03s

avrdude: verifying ...
avrdude: 1 bytes of hfuse verified
avrdude: reading input file "0x05"
avrdude: writing efuse (1 bytes):

Writing |                                                    | 0% 0.00s ***failed;
Writing | ################################################## | 100% 0.21s

avrdude: 1 bytes of efuse written
avrdude: verifying efuse memory against 0x05:
avrdude: load data efuse data from input file 0x05:
avrdude: input file 0x05 contains 1 bytes
avrdude: reading on-chip efuse data:

Reading | ################################################## | 100% 0.03s

avrdude: verifying ...
avrdude: verification error, first mismatch at byte 0x0000
         0xfd != 0x05
avrdude: verification error; content mismatch

avrdude: safemode: efuse changed! Was 5, and is now fd
Would you like this fuse to be changed back? [y/n]
```

**Comment by hadesbox** [comment]
Its fine that error. Im not super sure why the programmer sometimes can't verify everything, but fuses are set fine so its ok.

Burn the test sketch, for this you will need to put the potentiometers and the leds.

**Comment by hedefalk** [comment]
Great, thanks!
