### ISSUE TITLE
Tuning in software?

### ISSUE THREAD

**Issue by hedefalk** [Ttreintaysiete/ardcore#6]
Oh, maybe stupid question, but I just realized I only have 24k and no 24.9k 0603's so I looked closer at the schematic to see if it would be important and noticed that it's on the DAC output. So yeah.

And then I thought, but well, there ought to be a trimpot for tuning there. But there isn't? How would I go about tuning this one for a sketch like a quantizer which is my first intended use case? I guess I'd need to tune in software instead, possibly using the analog pots then and store in mem? Is there any code examples on this? I thought this was gonna be pretty compatible with original ardcore sketches. NP though, I guess it's fixable and I mostly wanna do my own software anyways, just wanted to know how you approached it?

**Comment by hadesbox** [comment]
Hi! So the ardcore its really fully compatible with all the sketches, you just need to change the DAC as specified so dont get scared there... The original arduino didn't have a stable voltage reference for the dac, this version does so you should be fine without any calibration.

In any case if you want to make super fine adjustments you can do it but cutting a trace and adding the trimmer.

<img width="412" alt="screen shot 01-13-18 at 12 28 pm" src="https://user-images.githubusercontent.com/475460/34905661-d2db04f4-f85d-11e7-95c1-5ee257dffd21.PNG">

So cutting in the trace in purple and changing the 100k resistor for a 80k resistor, and having a 50k trimmer should more than enough.

If you check the schematics on the original ardcore you can see how its wired... its to the resistor on the output to change the offset of dac... and thats it.

<img width="574" alt="screen shot 01-13-18 at 12 24 pm" src="https://user-images.githubusercontent.com/475460/34905667-108865d0-f85e-11e7-8126-61ea06f27980.PNG">

![ardcore](https://www.muffwiggler.com/forum/files/ardcore_200.jpg)

If you use the 24.9k you should not need to do anything of these, please test first yout module and let us know how it went. I really never have need to do any adjustments and dont recommend you to add a trimmer. 

If detuning its super bad let me know.

**Comment by hadesbox** [comment]
If you see the "euroardcore" it doesnt' have any trimmers too.

http://syinsi.com/projects/euroardcore/euroardcore-building-guide/

**Comment by hadesbox** [comment]
in our "Old" ardcore

**Comment by hadesbox** [comment]
Anyway if you want to try to make a software calibration you should try to use Braids (mutable instruments) algorithm.

https://github.com/pichenettes/eurorack/blob/2e09d0c20452763366d8aa490e41ac987fc0ebad/braids/ui.cc#L169-L180

Its the most copied algorithm from Olivier :). Its not super simple to implement but works great.. I haven't implement anything of this yet.

**Comment by hedefalk** [comment]
@hadesbox Thanks for all the info! Sounds awesome, really want to get started programming this thing soon!

But just want to double check - the schematic I have actually says 47K on R50 and 100k on R56 compared to the build instructions which says 24.9k on R50. That sounds like almost a twice the output amplification?

**Comment by hadesbox** [comment]
R50 is 24.9k, I checked on the eagle files and the BOM that I published and 24.9k its correct. What schematic you are using?

![1](https://user-images.githubusercontent.com/475460/34936859-2068796e-f9e3-11e7-9a46-3fc5ddfef7ac.png)

**Comment by hadesbox** [comment]
AHHHHHHHHHH now I remember sorry... bom and building docs are not updated.... the board files are correct, the resistance was increasted to 47K to improve gain on the output (double gain).

https://github.com/Ttreintaysiete/ardcore/commit/5caaa4181be58aee3b772caba368f5d56903072c

Check that commit comment. So with 24.9k works but with lower volume... to double amplitude you should use 47k.

**Comment by hedefalk** [comment]
Ah, cool! Thanks! 47K it is!
