### ISSUE TITLE
How it is ok for the regulator and MCU?

### ISSUE THREAD

**Issue by hedefalk** [Ttreintaysiete/ardcore#7]
Finished building my first unit and I have uploaded the led test sketch. It's working for 3 out of 4 leds:

https://photos.app.goo.gl/aBm5HXirTEnzTL9A3

I used my scope to debug and found that DIO6 wasn't soldered (man I had many bad points on the MCU apparantly). At first I could get the signal on top of the pin but not on the part of the pad that I could reach on the PCB. So I fluxed and resoldered.

After that however, I'm pretty sure that the solder point for DIO6 is ok, however now I don't even get a signal on the pin itself. The MCU is also pretty hot and the regulator is really hot - like "I don't wanna keep my finger on it too long" - hot. 

Did I finally managed to fry the MCU?

**Comment by hadesbox** [comment]
If its hot, then you have a short on that pin probably... my builds can be powered on for hours and not getting hot.

So check for shorts on that pin (or in the led, or in the jackoutput). Check for shorts agains +12v and -12v .  
Its very likely that pin is now dead, RIP.

**Comment by hadesbox** [comment]
if you have a amperimeter would be nice to measure wattage of the module... :)

This for instance is super handy (I dont have it, but I wish).

https://www.thonk.co.uk/shop/joranalogue-test-3-eurorack-kit/

**Comment by hadesbox** [comment]
With the potentiometers you should be able to control de speed of each led output, so try that!.

Another thing that is probable, is that the potentiometer for that output (A2) is not sending it signal to the MCU, or that its also shorted some how.

**Comment by hedefalk** [comment]
@hadesbox Yeah, ok, pin 10/DIO6 is grounded so that's explains both heat and no led.

However, there aren't any bridges so I guess it really has to be internal to the MCU? Or beneath the chip that I can't see. Or later in the output chain… Gonna inspect the drivers…

**Comment by hedefalk** [comment]
Seems I fried my arduino programmer too powering it… :'(

**Comment by hedefalk** [comment]
Yey, found it! Bridge on that channels output driver: 
![image](https://user-images.githubusercontent.com/116520/34980625-6d502e9e-faa5-11e7-89d8-60a763ed9985.png)

**Comment by hadesbox** [comment]
Yeah could be that via...


![captura de pantalla de 2018-01-16 10-08-20](https://user-images.githubusercontent.com/475460/34980697-8a62631c-faa5-11e7-8e15-64a27dfc7808.png)


but you shouldn't have problem becuse vias are tented (should be covered by solder mask).

**Comment by hadesbox** [comment]
AHHHHHHH Those little tribufferstate are also a pain to solder, its better to double check them all :)

**Comment by hedefalk** [comment]
Now I have 4 blinking LEDs! Yey! However, that one that was didn't blink at all doesn't seem to react to the pots, just blinking constantly slowly.

I'll check the pot reading too…

The LED's are super bright, will change to at least 300ohm or maybe even 400 for the next one. Can hardly see my computer screen right now :) I guess all leds are different, should have breadboarded this batch first :)


Ok, back to pots:

So turning them all up I have on the MCU:

23: 5V
24: 720mV
25: 5V
26: 5V

which is really weird becuase 24 is A1 which is for D1 in the sketch. However, this one actually does behave differently too. If I understand the sketch and reality, they blink slower the more clockwise (higher voltage) I turn them. A1/D1 however doesn't ever become really slow. And A2/D2 doesn't seem to react to the pot value at all even though that signal actually does come in fine to the MCU.

Love some debugging! At least it's not getting hot anymore :)

**Comment by hedefalk** [comment]
Ok, so the pot has still 5V on the viper, but after RC4 it has dropped as opposed to the other pots. I'm gonna check those diodes if I have bridged something there.

**Comment by hedefalk** [comment]
One of the diodes turned the wrong way. This is starting to get comedical, every mistake possible I have done :) But all fun and games!

**Comment by hadesbox** [comment]
Its normal to make some mistakes... the building docs are not very detailed and assume a lot of things.
But at least is a good way to learn (the hardway) a lot.

**Comment by hedefalk** [comment]
Yup, I'm  learning a lot :)

I'll just continue logging my debugging if that's ok.

So now I've turned that diode and I get 5V on all the analog input pins when fully clockwise. But now instead I have on 5V also on pin 25 when all are turned fully CCW - suspecting another wrongly turned diode, to GND this time…
